---
- hosts: localhost
  connection: local

  vars:
    ssh_key: etcd
    aws_region: us-east-1
    etcd_num_nodes: 2
    etcd_security_group_name: etcd
    etcd_template: ami-e965ba80 
    etcd_instance_type: t2.micro

  pre_tasks:
    - name: Get bootstrap token for etcd
      command: curl -w "\n" https://discovery.etcd.io/new
      register: token
    - debug: msg='Etcd token is {{ token.stdout }}'
    
  roles:
    - common-ec2
    - etcd-ec2
