---
- hosts: localhost
  connection: local
  vars:
    ssh_key: k8sec2
    aws_region: eu-east-1
    k8s_version: v1.1.3
    k8s_num_nodes: 2
    k8s_security_group_name: k8s
    k8s_template: ami-9063d5e3 
    k8s_instance_type: t2.micro

  roles:
    - common-ec2
    - k8s-ec2
