  - name: Start etcd nodes
    ec2:
      region: "{{ aws_region }}"
      image: "{{ etcd_template }}"
      instance_type: "{{ etcd_instance_type }}"
      key_name: "{{ ssh_key }}"
      group: "{{ etcd_security_group_name }}"
      user_data: "{{ lookup('template', '../templates/etcd.j2') }}"
      count: "{{ etcd_num_nodes }}"
      wait: yes
    register: ec2
    
  - name: check the public ip
    debug: msg=etcd node IP is "{{ item.public_ip }}"
    with_items: "{{ ec2.instances }}"
